### ISSUE TITLE
Hiding columns doesn't always work properly with manualColumnMove

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable-pro#25] opened 2017-12-18 14:31 UTC
When I manually move visible columns in a grid with hidden columns, it adds empty columns.

*Steps to reproduce:*

1. Go to: http://jsfiddle.net/1ze0twzp/
2. Move column C after E or G.
3. Result:

![screen shot 2017-12-18 at 15 29 18](https://user-images.githubusercontent.com/8048526/34110865-3c4c97aa-e408-11e7-97e5-597e5a559fee.png)

iOS, Chrome, Handsontable Pro 1.15.0

**Comment by AMBudnik** [comment] 2018-03-20 10:50
The issue is still replicable in v 0.38.1

When I move column `C` after `E`

![image.png](https://images.zenhubusercontent.com/5a96b5784b5806bc2bc8c7df/36d8a388-00cf-4e08-a463-05acfcba7322)

And here is `C` after `G`

![image.png](https://images.zenhubusercontent.com/5a96b5784b5806bc2bc8c7df/0abde5ea-53f9-4e0d-966c-fbd4ddd8ec13)

**Comment by AMBudnik** [comment] 2018-06-29 09:00
Thank you for sharing the tips and doing the investigation. I'd be happy to see a PR from you.

**Comment by salcio** [comment] 2018-07-31 13:07
Hi, 

When can we expect fix for this ? It's still reproducible in 5.0.0 ([jsFiddle](http://jsfiddle.net/dx85bnt9/6/))

**Comment by AMBudnik** [comment] 2018-08-14 07:04
We will try to schedule it for September.

**Comment by wojciechczerniak** [comment] 2019-02-25 11:18
Duplicate of https://github.com/handsontable/handsontable/issues/5598

**Closed by wojciechczerniak** 2019-02-25 11:18 UTC
Labels: Guess: a day or more, Plugin: hidden columns, Priority: high
